import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import { Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ScrollProvider } from "@/context";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import WagmiProviderComp from "@/wgami-provider";

export const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={roboto.className}>
   
        <WagmiProviderComp initialState={initialState}>
          <NextUIProvider>
            <ScrollProvider>{children}</ScrollProvider>
          </NextUIProvider>
        </WagmiProviderComp>
      </body>
    </html>
  );
}
